hackmcgill/hackerAPI

package.json

add --exit to tests

---

controllers/account.controller.js
controllers/hacker.controller.js
controllers/sponsor.controller.js
controllers/team.controller.js
controllers/volunteer.controller.js
middlewares/account.middleware.js
middlewares/hacker.middleware.js
middlewares/sponsor.middleware.js
middlewares/team.middleware.js
middlewares/volunteer.middleware.js
services/account.service.js
services/hacker.service.js
services/skill.service.js
services/sponsor.service.js
services/team.service.js
services/volunteer.service.js

Update req type in comments, change id type from string and MongoId to ObjectId.

Update req type in comments, change id type from string to ObjectId

---

docs/architecture.md
docs/index.md

@pavelkondratyev can you have a look at how I described `search` and let me know if there are any fixes that need to be made?

Add architecture file to documentation

---

middlewares/auth.middleware.js
middlewares/hacker.middleware.js
middlewares/sponsor.middleware.js
routes/api/hacker.js
routes/api/sponsor.js
services/hacker.service.js
services/sponsor.service.js
tests/email.service.spec.js
tests/hacker.test.js
tests/search.service.spec.js
tests/sponsor.test.js
tests/util/hacker.test.util.js
tests/util/roleBinding.test.util.js
tests/util/sponsor.test.util.js

Add duplicate accountId checking logic for sponsors

---

middlewares/hacker.middleware.js
middlewares/sponsor.middleware.js
middlewares/volunteer.middleware.js
routes/api/volunteer.js
services/hacker.service.js
services/sponsor.service.js
services/volunteer.service.js
tests/util/roleBinding.test.util.js
tests/util/volunteer.test.util.js
tests/volunteer.test.js

#102 
linting, volunteer accountID check, commenting, change findByAccountId logic to reflect findOne call,

Finish up checking for already linked accountId feature

---

middlewares/account.middleware.js
middlewares/hacker.middleware.js
middlewares/validators/account.validator.js
middlewares/validators/hacker.validator.js
middlewares/validators/validator.helper.js
models/account.model.js
models/hacker.model.js
tests/hacker.test.js
tests/util/account.test.util.js
tests/util/hacker.test.util.js

#97 
Update Hacker and Account schemas to meet requirements from MLH. Made appropriate changes to middleware and tests as well. Removed some unused code.

Feature #97 Update Hacker and Account schemas to meet MLH requirements

---

.vscode/launch.json
assets/email/AccountConfirmation.hbs
assets/email/ResetPassword.hbs
assets/email/statusEmail/Accepted.hbs
assets/email/statusEmail/Accepted.html
assets/email/statusEmail/Applied.hbs
assets/email/statusEmail/Applied.html
assets/email/statusEmail/Cancelled.hbs
assets/email/statusEmail/Cancelled.html
assets/email/statusEmail/Checked-in.hbs
assets/email/statusEmail/Checked-in.html
assets/email/statusEmail/Confirmed.hbs
assets/email/statusEmail/Confirmed.html
assets/email/statusEmail/None.hbs
assets/email/statusEmail/None.html
assets/email/statusEmail/Waitlisted.hbs
assets/email/statusEmail/Waitlisted.html
assets/email/test.hbs
controllers/hacker.controller.js
middlewares/hacker.middleware.js
package-lock.json
package.json
services/accountConfirmation.service.js
services/email.service.js
services/resetPassword.service.js
tests/email.service.spec.js

Fixes the currently open issue: #123

Migrate email services to handlebars rendering

---

constants/role.constant.js
docs/getting-started.md
docs/index.md
package.json
seed/index.js
seed/roles.seed.js

Create seed file that will add all roles to a given database. To do this, run `npm run seed` in the root directory. To change which db this seeds to, go to `package.json` and change `NODE_ENV=` to whichever environment you want.
Fixes #151

Add seed file for Roles

---

.env.example
constants/general.constant.js

Move hackathon name to constants file

---

middlewares/auth.middleware.js

Adds a check if account is confirmed to avoid sending a confirmation email

161-ConfirmAccountMiddlewareBug fix

---

app.js

Add cors options

---

assets/email/AccountInvitation.hbs
constants/general.constant.js
constants/routes.constant.js
controllers/account.controller.js
middlewares/account.middleware.js
middlewares/validators/account.validator.js
middlewares/validators/validator.helper.js
routes/api/account.js
services/accountConfirmation.service.js
tests/account.test.js
tests/util/accountConfirmation.test.util.js

Resolves #15, #85 
Logic to create a token and send an email to a user to allow them to create an account

15-Account invitation logic

---

.gitignore
apidoc.json
docs/api/api_data.js
docs/api/api_data.json
docs/api/api_project.js
docs/api/api_project.json
middlewares/auth.middleware.js
services/resetPassword.service.js

Fix reset password route

---

middlewares/validators/search.validator.js
middlewares/validators/validator.helper.js
models/hacker.model.js
tests/search.service.spec.js

Resolves #141 
Fixed validation bug, as well as adjusted unit tests to account for validation errors.
Also changed validation to have more informative messages.

141 - Query Validation Bug

---

constants/role.constant.js
constants/routes.constant.js
controllers/hacker.controller.js
docs/api/api_data.js
docs/api/api_data.json
docs/api/api_project.js
docs/api/api_project.json
middlewares/hacker.middleware.js
routes/api/hacker.js
tests/hacker.test.js

Create a route for a logged in hacker to view their own information.
Fixes #175 
Create a unit test for a hacker to view their own information.
Create a unit test for an Admin to be unable to view this as they are not a type hacker.

create /hacker/self method for logged in hacker to view their own info

---

.vscode/settings.json
assets/email/AccountConfirmation.hbs
assets/email/AccountInvitation.hbs
assets/email/ResetPassword.hbs
assets/email/test.hbs
middlewares/account.middleware.js
middlewares/auth.middleware.js
services/accountConfirmation.service.js
services/resetPassword.service.js
tests/email.service.spec.js

Fix additional bugs with respect to emails, resetting password

---

app.js

We broke CORS again, so this is a fix for that.
Users must add the following to their environment files:
```
#front-end server
FRONTEND_ADDRESS_DEV=localhost:1337
#front-end server
FRONTEND_ADDRESS_DEPLOY=app.mchacks.ca
```
Fixes #163 
Tested locally with frontend.

Quick fix for CORS error

---

app.js
tests/search.service.spec.js

Validation errors were nested inside of the data / message object. This should fix that issue.
Fixes # (issue)
Tested on frontend via postman, and also unit tests.

Fix how we send back errors so that the format is more consistent

---

assets/email/AccountConfirmation.hbs
assets/email/AccountInvitation.hbs
assets/email/ResetPassword.hbs
assets/email/statusEmail/Accepted.hbs
assets/email/statusEmail/Applied.hbs
assets/email/statusEmail/Cancelled.hbs
assets/email/statusEmail/Checked-in.hbs
assets/email/statusEmail/Confirmed.hbs
assets/email/statusEmail/None.hbs
assets/email/statusEmail/Waitlisted.hbs

- updated email styling
- made css inline for styling to work in Gmail
- changed image url to host from static site
- changed image type to png since svg wouldn't show up
Issue that still exists:
- firstName not populating in email
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

Update emails to inline css

---

middlewares/validators/validator.helper.js
models/hacker.model.js
routes/api/hacker.js

Users should not be able to redefine the internal value of resume. Therefore, we must remove it from validation.

Remove input to resume link in create / patch

---

middlewares/hacker.middleware.js
routes/api/hacker.js

Add middleware to send status applied email on hacker creation.

Add new middleware that blindly sends the HACKER_STATUS_APPLIED email

---

services/accountConfirmation.service.js

Change frontend URL in invite email
Fixes #281 
Not tested.

Change link

---

assets/email/statusEmail/Accepted.hbs

changed to Friday, January 25 for final round of decisions
Fixes # (issue)
closes #301
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

update date to fri jan 25

---

scripts/batch_update.py

Python script to update hacker statuses in bulk.
Fixes #307
On production, lol

Add batch script to update hacker statuses

---

constants/role.constant.js

Add the search role to sponsor.

Add search to sponsor

---

assets/email/Ticket.hbs
services/hacker.service.js

Partial completion of #312 
Using Postman

Update week-of email

---

assets/email/Welcome.hbs
constants/routes.constant.js
constants/success.constant.js
controllers/hacker.controller.js
docs/api/api_data.js
docs/api/api_data.json
docs/api/api_project.js
docs/api/api_project.json
middlewares/hacker.middleware.js
routes/api/hacker.js
scripts/batch_update.py
services/email.service.js
tests/hacker.test.js
tests/util/hacker.test.util.js

Add day-of email, update batch script

---

middlewares/account.middleware.js
middlewares/hacker.middleware.js
middlewares/sponsor.middleware.js
middlewares/team.middleware.js
middlewares/volunteer.middleware.js

Move all non-200 status messages to the error router.
Fixes # (issue)

Make error routing use the error handler

---

models/accountConfirmationToken.model.js

Noticed the linking in the schema wasn't working properly.
No new tests.

Fix linking of accountType in account confirmation token schema

---

seed/index.js
seed/roles.seed.js

When seeding, process should now exit afterwards.

Clean up code in seed files

---

docs/standards.md

Added documentation for PRs, and code review.
Fixes #395 
Documentation only.
N/A

Add section for PRs, Code Review

---

docs/getting-started.md
docs/standards.md

Updates the documentation for the batch scripts found in [this file](https://github.com/hackmcgill/hackerAPI/blob/develop/scripts/batch_scripts.py).
Fixes #462

Add documentation for the batch scripts

---

routes/api/account.js
routes/api/auth.js
routes/api/hacker.js
routes/api/sponsor.js
routes/api/team.js
routes/api/volunteer.js

Moving the idValidator before the authorization middleware
Fixes # 286
TBH not sure how to run the tests, first issue so please lemme know

Fix #286 put idValidator before authorization

---

.travis.yml

- Add Travis notifications to Slack
- Works for any channel

Add Travis notifications to Slack

---

.vscode/launch.json

No ticket available.
Fix debug suite.
Verify manually that you can now run the debug suite on VSCode.

Change tdd to bdd to fix debug file

---

.github/CHANGELOG.md
constants/general.constant.js
tests/util/hacker.test.util.js

-   HCK-198
Relates to https://github.com/hackmcgill/dashboard/pull/749
- Change job interest enum from `Full-time` to `Full Time`
- Update hacker tests to use new enum
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Filled out application and tried all 3 job interest enums
-   [ ] I have made corresponding changes …

Change job interest enum

---

.github/CHANGELOG.md
assets/email/marketingEmail/3Days.hbs
assets/email/marketingEmail/EmailBlast.hbs

- Add 3 days left marketing email to `/marketingEmail`
- Fix unsubscribe button in marketing emails
-   [x] New feature (non-breaking change which adds functionality)
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] My changes generate no new warnings
-   [x] Listed change(s) in the Changelog
-   [ ] I have made corresponding changes to the documentation
-   [ ] Any dependent changes have been merged and published in downstream modules

Add 3 days left marketing email

---

.github/CHANGELOG.md
constants/role.constant.js

Removed travel routes that could access any hacker from constants file.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] I have made corresponding changes to the documentation
-   [ ] Any dependent changes have been merged and published in downstream modules

Removed travel permissions from hacker

---

constants/role.constant.js
constants/routes.constant.js
docs/architecture.md

-   fixes #651
- Added `_id` attribute to every route
- Use `_id` of the route as the `_id` of a single role
- Fix some vulnerabilities with object.prototype methods.
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected): running `npm run seed` will break all auth bindings for single roles. We will need to manually fix this. @krubenok.
-   [x] This change requires a documentation update [DONE]
Manually ran `npm run seed` on a local instance. Everything worked!
-   [x] My code follows the style guidelines of this project
- …

feat: fix non-determinism of npm run seed (Bugfix/651)

---

.vscode/launch.json

Quality of life fix so that my code doesn't crash all the time when running the debugger :(

feat: Add runtimeVersion which matches .nvmrc

---

package-lock.json
package.json
services/logger.service.js

- #676
- `npm audit fix`
- `npm update yargs-parser --depth 3`
- `npm update dot-prop --depth 4`
- `npm install --save-dev nodemon@2.0.6`
- remove gcp logging-winston library because we no longer host on GCP
- `npm install @google-cloud/storage@5.5.0`
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   Unit tests
-   [x] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [x] I have commented my code, …

fix: fix dependencies in hackerAPI

---

constants/general.constant.js
middlewares/account.middleware.js
middlewares/auth.middleware.js
models/accountConfirmationToken.model.js
services/accountConfirmation.service.js
tests/account.test.js
tests/util/accountConfirmation.test.util.js

#680
- fix: add confirmationType to confirmation token
- feat: filter by type when returning invites
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [X] Unit tests
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] Listed change(s) in the Changelog
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] I have made corresponding changes to the documentation
-   [x] Any dependent …

fix: add confirmationType to confirmation token, and filter by type when returning invites

---

models/emailTemplate.model.js
scripts/migrate_email_templates.js

…g email templates
-   [HCK-17](https://linear.app/hackmcgill/issue/HAC-17/move-email-templates-to-database)
- added email template model
- created a script to move [existing templates](https://github.com/hackmcgill/hackerAPI/tree/dev/assets/email/marketingEmail) to database
-   [ ] Ran `NODE_ENV=test && node ./scripts/migrate_email_templates.js` manually
**Firmware version:**
**Hardware:**
**Toolchain:**
**SDK:**
-   [ ] I have …

feat: email template model, migration script for marketing templates

---

package.json

-   [HAC-33](https://linear.app/hackmcgill/issue/HAC-33/create-windows-npm-script)
- added a `start-windows` script to `package.json`
-   [ ] running `npm run start-windows` on Windows 10
**Firmware version:**
**Hardware:**
**Toolchain:**
**SDK:**
-   [ ] I have made corresponding …

feat: add start-windows script

---

package.json
tests/email.service.spec.js
tests/storage.spec.js

-   HAC-
- Github action was not properly loading environment variable when  running test, this fixes that
- After migrating away from Travis CI, github action didn't properly load env vars. No longer specifying path to env to fix this issue.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] New release
-   [ ] This change requires a documentation update
Please describe the tests that …

fix: properly load env in ci

---

.gitignore
constants/role.constant.js
constants/routes.constant.js
middlewares/hacker.middleware.js
package-lock.json
routes/api/hacker.js

- Add a unique route for verification of hacker status when they join the McHacks 9 discord.
- Change hacker status from confirmed to Checked-In when this happens (emulating the QR code scanning functionality).
-   [X] New feature (non-breaking change which adds functionality)
-   [X] This change requires a documentation update
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings
-   [X] New and existing unit tests pass locally with my changes
-   [ ] I have made corresponding changes to …

feat(hacker.js,hacker.middleware.js): add ability for discord verification.

---

assets/email/statusEmail/Checked-in.hbs

-   HAC-
-
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] New release
-   [ ] This change requires a documentation update
-   [ ] Test A
-   [ ] Test B
**Firmware version:**
**Hardware:** …

change invite to disc

---

.gitignore
assets/email/AccountInvitation.hbs
assets/email/Ticket.hbs
assets/email/Welcome.hbs
assets/email/marketingEmail/3Days.hbs
assets/email/marketingEmail/EmailBlast.hbs
assets/email/statusEmail/Accepted.hbs
assets/email/statusEmail/Applied.hbs
assets/email/statusEmail/Checked-in.hbs
constants/role.constant.js
constants/routes.constant.js
middlewares/hacker.middleware.js
package-lock.json
routes/api/hacker.js

-   HAC-
-
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] New release
-   [ ] This change requires a documentation update
-   [ ] Test A
-   [ ] Test B
**Firmware version:**
**Hardware:** …

chore: merge dev to main

---

middlewares/travel.middleware.js
middlewares/validators/hacker.validator.js
models/hacker.model.js
models/travel.model.js
package.json

- #921 
- Modified `Hacker` model to include a reason in addition to the reimbursement amount.
-   [X] New feature (non-breaking change which adds functionality)
-   [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [X] This change requires a documentation update
-   [ ] I have made corresponding changes to the …

Add field for reimbursement reason
